[package]
name = "algs"
version = "0.1.0"
authors = ["iy"]
edition = "2018"

[[bin]]
name = "fib"
path = "src/fib.rs"

[[bin]]
name = "gcd"
path = "src/gcd.rs"

[[bin]]
name = "list"
path = "src/linked_list.rs"

[[bin]]
name = "fib_iter"
path = "src/fib_iterator.rs"

# SORTING
[[bin]]
name = "bubble"
path = "src/sorting/bubble.rs"

[[bin]]
name = "quick"
path = "src/sorting/quick.rs"

[[bin]]
name = "quick_closure"
path = "src/sorting/quick_closure.rs"

[[bin]]
name = "count"
path = "src/sorting/counting.rs"

[[bin]]
name = "insertion"
path = "src/sorting/insertion.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
num  = "0.2"